/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'AttendanceStatus': { name: 'AttendanceStatus'; enumValues: 'NOT_ATTENDED' | 'STUDYING' | 'COMPLETED' | 'LATE' | 'VACATION'; };
    'AttendanceSummary': { kind: 'OBJECT'; name: 'AttendanceSummary'; fields: { 'attended': { name: 'attended'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'late': { name: 'late'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'studying': { name: 'studying'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'CalendarDay': { kind: 'OBJECT'; name: 'CalendarDay'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AttendanceStatus'; ofType: null; }; } }; }; };
    'DailyVacation': { kind: 'OBJECT'; name: 'DailyVacation'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'hours': { name: 'hours'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'DayDetailResult': { kind: 'OBJECT'; name: 'DayDetailResult'; fields: { 'sessions': { name: 'sessions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; }; }; } }; 'totalDurationMinutes': { name: 'totalDurationMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'vacationHours': { name: 'vacationHours'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'FeeStatusEntry': { kind: 'OBJECT'; name: 'FeeStatusEntry'; fields: { 'isPaid': { name: 'isPaid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateFee': { name: 'lateFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'member': { name: 'member'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; } }; 'monthlyFee': { name: 'monthlyFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ID': unknown;
    'Int': unknown;
    'Member': { kind: 'OBJECT'; name: 'Member'; fields: { 'color': { name: 'color'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'currentStatus': { name: 'currentStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AttendanceStatus'; ofType: null; }; } }; 'displayName': { name: 'displayName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'todayStudyMinutes': { name: 'todayStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'MonthlyFee': { kind: 'OBJECT'; name: 'MonthlyFee'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isPaid': { name: 'isPaid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'month': { name: 'month'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'MonthlySummaryResult': { kind: 'OBJECT'; name: 'MonthlySummaryResult'; fields: { 'attendanceDays': { name: 'attendanceDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'averageDailyMinutes': { name: 'averageDailyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'totalLateFee': { name: 'totalLateFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'totalStudyMinutes': { name: 'totalStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'vacationDays': { name: 'vacationDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { '_empty': { name: '_empty'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'checkIn': { name: 'checkIn'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; } }; 'checkOut': { name: 'checkOut'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; } }; 'toggleFeePayment': { name: 'toggleFeePayment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlyFee'; ofType: null; }; } }; 'useVacation': { name: 'useVacation'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DailyVacation'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { '_empty': { name: '_empty'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'calendar': { name: 'calendar'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CalendarDay'; ofType: null; }; }; }; } }; 'dayDetail': { name: 'dayDetail'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DayDetailResult'; ofType: null; }; } }; 'feeStatus': { name: 'feeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FeeStatusEntry'; ofType: null; }; }; }; } }; 'memberRanking': { name: 'memberRanking'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RankingEntry'; ofType: null; }; }; }; } }; 'members': { name: 'members'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; }; }; } }; 'monthlySummary': { name: 'monthlySummary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlySummaryResult'; ofType: null; }; } }; 'todayAttendanceSummary': { name: 'todayAttendanceSummary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AttendanceSummary'; ofType: null; }; } }; }; };
    'RankingEntry': { kind: 'OBJECT'; name: 'RankingEntry'; fields: { 'attendanceDays': { name: 'attendanceDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'member': { name: 'member'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; } }; 'totalStudyMinutes': { name: 'totalStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'RankingPeriod': { name: 'RankingPeriod'; enumValues: 'WEEKLY' | 'MONTHLY'; };
    'Session': { kind: 'OBJECT'; name: 'Session'; fields: { 'checkInTime': { name: 'checkInTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'checkOutTime': { name: 'checkOutTime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'durationMinutes': { name: 'durationMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isLate': { name: 'isLate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'String': unknown;
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}