/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'AttendanceStatus': { name: 'AttendanceStatus'; enumValues: 'COMPLETED' | 'LATE' | 'NOT_ATTENDED' | 'STUDYING' | 'VACATION'; };
    'AttendanceSummary': { kind: 'OBJECT'; name: 'AttendanceSummary'; fields: { 'attended': { name: 'attended'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'late': { name: 'late'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'studying': { name: 'studying'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'CalendarDay': { kind: 'OBJECT'; name: 'CalendarDay'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AttendanceStatus'; ofType: null; }; } }; }; };
    'DailyVacation': { kind: 'OBJECT'; name: 'DailyVacation'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'hours': { name: 'hours'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'DayDetailResult': { kind: 'OBJECT'; name: 'DayDetailResult'; fields: { 'sessions': { name: 'sessions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; }; }; } }; 'totalDurationMinutes': { name: 'totalDurationMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'vacationHours': { name: 'vacationHours'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'FeeStatusEntry': { kind: 'OBJECT'; name: 'FeeStatusEntry'; fields: { 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateFee': { name: 'lateFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateFeeStatus': { name: 'lateFeeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PaymentStatus'; ofType: null; }; } }; 'member': { name: 'member'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; } }; 'monthlyFee': { name: 'monthlyFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'monthlyFeeStatus': { name: 'monthlyFeeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PaymentStatus'; ofType: null; }; } }; }; };
    'FeeType': { name: 'FeeType'; enumValues: 'LATE' | 'MONTHLY'; };
    'ID': unknown;
    'Int': unknown;
    'Invite': { kind: 'OBJECT'; name: 'Invite'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createdBy': { name: 'createdBy'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'expiresAt': { name: 'expiresAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'token': { name: 'token'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'workspaceId': { name: 'workspaceId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Member': { kind: 'OBJECT'; name: 'Member'; fields: { 'color': { name: 'color'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'currentStatus': { name: 'currentStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AttendanceStatus'; ofType: null; }; } }; 'displayName': { name: 'displayName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'MemberRole'; ofType: null; }; } }; 'todayStudyMinutes': { name: 'todayStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'todayVacationHours': { name: 'todayVacationHours'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'MemberRole': { name: 'MemberRole'; enumValues: 'ADMIN' | 'MEMBER'; };
    'MonthlyFee': { kind: 'OBJECT'; name: 'MonthlyFee'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'lateFeeStatus': { name: 'lateFeeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PaymentStatus'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'month': { name: 'month'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'monthlyFeeStatus': { name: 'monthlyFeeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PaymentStatus'; ofType: null; }; } }; }; };
    'MonthlySummaryResult': { kind: 'OBJECT'; name: 'MonthlySummaryResult'; fields: { 'attendanceDays': { name: 'attendanceDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'averageDailyMinutes': { name: 'averageDailyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'totalLateFee': { name: 'totalLateFee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'totalStudyMinutes': { name: 'totalStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'vacationDays': { name: 'vacationDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'cancelVacation': { name: 'cancelVacation'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'checkIn': { name: 'checkIn'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; } }; 'checkOut': { name: 'checkOut'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; } }; 'confirmFeePayment': { name: 'confirmFeePayment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlyFee'; ofType: null; }; } }; 'createInvite': { name: 'createInvite'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Invite'; ofType: null; }; } }; 'createWorkspace': { name: 'createWorkspace'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Workspace'; ofType: null; }; } }; 'joinWorkspace': { name: 'joinWorkspace'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WorkspaceMemberObject'; ofType: null; }; } }; 'rejectFeePayment': { name: 'rejectFeePayment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlyFee'; ofType: null; }; } }; 'requestFeePayment': { name: 'requestFeePayment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlyFee'; ofType: null; }; } }; 'updateLateFeeAmount': { name: 'updateLateFeeAmount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Settings'; ofType: null; }; } }; 'updateMemberRole': { name: 'updateMemberRole'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; } }; 'updateMonthlyFeeAmount': { name: 'updateMonthlyFeeAmount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Settings'; ofType: null; }; } }; 'updateStudyStartTime': { name: 'updateStudyStartTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Settings'; ofType: null; }; } }; 'useVacation': { name: 'useVacation'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DailyVacation'; ofType: null; }; } }; 'useVacations': { name: 'useVacations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UseVacationsResult'; ofType: null; }; } }; }; };
    'PaymentStatus': { name: 'PaymentStatus'; enumValues: 'PAID' | 'PENDING' | 'UNPAID'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'activeSession': { name: 'activeSession'; type: { kind: 'OBJECT'; name: 'Session'; ofType: null; } }; 'calendar': { name: 'calendar'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CalendarDay'; ofType: null; }; }; }; } }; 'dayDetail': { name: 'dayDetail'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DayDetailResult'; ofType: null; }; } }; 'feeStatus': { name: 'feeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FeeStatusEntry'; ofType: null; }; }; }; } }; 'me': { name: 'me'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'memberRanking': { name: 'memberRanking'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RankingEntry'; ofType: null; }; }; }; } }; 'members': { name: 'members'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; }; }; } }; 'monthlySummary': { name: 'monthlySummary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MonthlySummaryResult'; ofType: null; }; } }; 'myWorkspaces': { name: 'myWorkspaces'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WorkspaceMemberObject'; ofType: null; }; }; }; } }; 'settings': { name: 'settings'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Settings'; ofType: null; }; } }; 'todayAttendanceSummary': { name: 'todayAttendanceSummary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AttendanceSummary'; ofType: null; }; } }; 'workspace': { name: 'workspace'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Workspace'; ofType: null; }; } }; 'workspaceMembers': { name: 'workspaceMembers'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WorkspaceMemberObject'; ofType: null; }; }; }; } }; }; };
    'RankingEntry': { kind: 'OBJECT'; name: 'RankingEntry'; fields: { 'attendanceDays': { name: 'attendanceDays'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lateCount': { name: 'lateCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'member': { name: 'member'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Member'; ofType: null; }; } }; 'totalStudyMinutes': { name: 'totalStudyMinutes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'RankingPeriod': { name: 'RankingPeriod'; enumValues: 'MONTHLY' | 'WEEKLY'; };
    'Session': { kind: 'OBJECT'; name: 'Session'; fields: { 'checkInTime': { name: 'checkInTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'checkOutTime': { name: 'checkOutTime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'durationMinutes': { name: 'durationMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isLate': { name: 'isLate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'Settings': { kind: 'OBJECT'; name: 'Settings'; fields: { 'lateFeeAmount': { name: 'lateFeeAmount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'monthlyFeeAmount': { name: 'monthlyFeeAmount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'studyStartHour': { name: 'studyStartHour'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'studyStartMinute': { name: 'studyStartMinute'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'workspaceId': { name: 'workspaceId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'String': unknown;
    'UseVacationsResult': { kind: 'OBJECT'; name: 'UseVacationsResult'; fields: { 'failed': { name: 'failed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'VacationFailure'; ofType: null; }; }; }; } }; 'succeeded': { name: 'succeeded'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DailyVacation'; ofType: null; }; }; }; } }; }; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'avatarUrl': { name: 'avatarUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'provider': { name: 'provider'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'VacationFailure': { kind: 'OBJECT'; name: 'VacationFailure'; fields: { 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'reason': { name: 'reason'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Workspace': { kind: 'OBJECT'; name: 'Workspace'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'ownerId': { name: 'ownerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'slug': { name: 'slug'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'WorkspaceMemberObject': { kind: 'OBJECT'; name: 'WorkspaceMemberObject'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'joinedAt': { name: 'joinedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'memberId': { name: 'memberId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'workspaceId': { name: 'workspaceId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}